- name: Stelle den Standardpfad zur Vault-Passwortdatei bereit
  set_fact:
    vault_password_file: "{{ sot_config.opt_data_dir + '/vault_pass.txt' }}"
  when: vault_password_file is not defined

- name: Übernehme den Pfad zur verschlüsselten Vault-Datei aus der Konfiguration
  set_fact:
    vault_file: "{{ sot_config.vault_file }}"

- name: Entschlüsseln der Vault-Datei
  command: >
    ansible-vault view "{{ vault_file }}"
    --vault-password-file="{{ vault_password_file }}"
  register: decrypted_vault
  changed_when: false

- name: Parsen des entschlüsselten Vault-Inhalts in Variablen
  set_fact:
    vault_vars: "{{ decrypted_vault.stdout | from_yaml }}"

- name: Setze Variablen aus der Vault-Datei
  set_fact:
    db_password: "{{ vault_vars.db_password | default('default_password') }}"
    api_key: "{{ vault_vars.api_key | default('default_api_key') }}"
    server_name: "{{ vault_vars.server_name | default(sot_config.system_name) }}"
    user_name: "{{ vault_vars.user_name | default(sot_config.username) }}"
    server_ip: "{{ vault_vars.server_ip | default('default_server_ip') }}"
    server_email: "{{ vault_vars.server_email | default(sot_config.vault_mail) }}"
    opt_data_dir: "{{ vault_vars.opt_data_dir | default(sot_config.opt_data_dir) }}"
    system_name: "{{ vault_vars.system_name | default(sot_config.system_name) }}"
    username: "{{ vault_vars.username | default(sot_config.username) }}"
    log_level: "{{ vault_vars.log_level | default(sot_config.log_level) }}"
    log_file: "{{ vault_vars.log_file | default(sot_config.log_file) }}"
    os_family: "{{ vault_vars.os_family | default('default_os_family') }}"
    kernel_version: "{{ vault_vars.kernel_version | default('default_kernel_version') }}"

- name: Zeige alle geladenen Variablen
  debug:
    msg: "{{ vars | to_yaml }}"
