- name: Stelle den Standardpfad zur Vault-Passwortdatei bereit
  set_fact:
    vault_password_file: "{{ sot_config.opt_data_dir + '/vault_pass.txt' }}"
  when: vault_password_file is not defined

- name: Übernehme den Pfad zur verschlüsselten Vault-Datei aus der Konfiguration
  set_fact:
    vault_file: "{{ sot_config.vault_file }}"

- name: Entschlüsseln der Vault-Datei
  command: >
    ansible-vault view "{{ vault_file }}"
    --vault-password-file="{{ vault_password_file }}"
  register: decrypted_vault
  changed_when: false

- name: Parsen des entschlüsselten Vault-Inhalts in Variablen
  set_fact:
    vault_vars: "{{ decrypted_vault.stdout | from_yaml }}"

- name: Setze Variablen aus der Vault-Datei
  set_fact:
    db_password: "{{ vault_vars.get('db_password', 'default_password') }}"
    api_key: "{{ vault_vars.get('api_key', 'default_api_key') }}"
    server_name: "{{ vault_vars.get('server_name', sot_config.system_name) }}"
    user_name: "{{ vault_vars.get('user_name', sot_config.username) }}"
    server_ip: "{{ vault_vars.get('server_ip', 'default_server_ip') }}"
    server_email: "{{ vault_vars.get('server_email', sot_config.vault_mail) }}"
    opt_data_dir: "{{ vault_vars.get('opt_data_dir', sot_config.opt_data_dir) }}"
    system_name: "{{ vault_vars.get('system_name', sot_config.system_name) }}"
    username: "{{ vault_vars.get('username', sot_config.username) }}"
    log_level: "{{ vault_vars.get('log_level', sot_config.log_level) }}"
    log_file: "{{ vault_vars.get('log_file', sot_config.log_file) }}"
    os_family: "{{ vault_vars.get('os_family', 'default_os_family') }}"
    kernel_version: "{{ vault_vars.get('kernel_version', 'default_kernel_version') }}"

- name: Zeige alle geladenen Variablen
  debug:
    msg: "{{ vars | to_yaml }}"
